version: '2'
services:
    jeanne2-app:
        image: jeanne2
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jeanne2-mysql:3306/jeanne2?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jeanne2-elasticsearch:9300
        ports:
            - 8080:8080
    jeanne2-mysql:
        extends:
            file: mysql.yml
            service: jeanne2-mysql
    jeanne2-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jeanne2-elasticsearch
